Repository ClearlyEnergy/django-helpdesk, pull requests merged in 2025-02, with the labels that each got.

#37 Allow for helpdesk ticket response window to be made larger
  helpdesk/templates/helpdesk/include/comment_md_preview.html
Labels: Awaiting review

#38 update: open attachments in new tab
  helpdesk/templates/helpdesk/ticket.html
  helpdesk/templates/helpdesk/ticket_desc_table.html
Labels: Awaiting review

#45 Form Fields: Prepopulation + Derived Column Fields
  helpdesk/forms.py
  helpdesk/lib.py
  helpdesk/migrations/0108_prepopulation.py
  helpdesk/migrations/0109_derived_column_field.py
  helpdesk/models.py
  helpdesk/templates/helpdesk/create_ticket.html
  helpdesk/templates/helpdesk/edit_ticket.html
  helpdesk/templates/helpdesk/include/derived_column_widget.html
  helpdesk/templates/helpdesk/include/prepopulate_form_input.html
  helpdesk/templates/helpdesk/public_create_ticket_base.html
  helpdesk/urls.py
  helpdesk/views/abstract_views.py
  helpdesk/views/public.py
  helpdesk/views/staff.py
Labels: enhancement, Awaiting review

#47 Payment Portal: Initial commit
  helpdesk/admin.py
  helpdesk/forms.py
  helpdesk/management/commands/check_orders.py
  helpdesk/migrations/0110_order_ordersettings.py
  helpdesk/models.py
  helpdesk/templates/helpdesk/payment.html
  helpdesk/templates/helpdesk/payment_canceled.html
  helpdesk/templates/helpdesk/payment_complete.html
  helpdesk/templates/helpdesk/payment_duplicate.html
  helpdesk/templates/helpdesk/payment_failed.html
  helpdesk/templates/helpdesk/payment_settings.html
  helpdesk/templates/helpdesk/system_settings.html
  helpdesk/urls.py
  helpdesk/views/public.py
  helpdesk/views/staff.py
Labels: Ready to merge
